###############################################
#  _______                                    #
#  ___    |___  ___________________________ _ #
#  __  /| |  / / /_  ___/  __ \_  ___/  __ `/ #
#  _  ___ / /_/ /_  /   / /_/ /  /   / /_/ /  #
# /_/  |_\__,_/ /_/    \____//_/    \__,_/    #
###############################################

remote:
  # Whether or not remote control via an HTTP server is enabled
  enabled: true
  # The ip that the server will listen on.
  # When left on auto, the plugin will try and figure the server's network ip.
  httpHostname: auto
  httpPort: 8001
  solarflare:
    enabled: false
    providedHostname: auto
    url: "http://visuals.madzoo.events/register"
