##################################################################
#  __________            _________             _________         #
#  ___  ____/____  ________  ____/_____ _____________  /____  __ #
#  __  __/  __  / / /  _ \  /    _  __ `/_  __ \  __  /__  / / / #
#  _  /___  _  /_/ //  __/ /___  / /_/ /_  / / / /_/ / _  /_/ /  #
#  /_____/  _\__, / \___/\____/  \__,_/ /_/ /_/\__,_/  _\__, /   #
#           /____/                                     /____/    #
##################################################################

remote:
  # Whether or not remote control via an HTTP server is enabled
  enabled: true
  httpHostname: 0.0.0.0
  httpPort: 8001
