name: Aurora
version: @version@
main: fyi.sorenneedscoffee.aurora.Aurora
api-version: 1.13
depend: [ ProtocolLib ]
authors: [ SorenNeedsCoffee ]
description: oooo, pretty lights
commands:
  point:
    description: Points control
    usage: "§cUsage: /<command> [add (x, y, z) | remove <id> | reload | list]"
  effects:
    description: Effects control
