name: Aurora
version: @version@
main: digital.murl.aurora.Aurora
api-version: 1.13
depend: [ ProtocolLib ]
authors: [ MurlDigital ]
description: oooo, pretty lights
commands:
  point:
    description: Points control
    usage: "§cUsage: /<command> [add (x, y, z) | remove <id> | reload | list | show [prefix] [suffix] | hide]"
  effects:
    description: Effects control
